// AUTO-GENERATED by corpora/build_site_data.py — do not hand-edit.
// Per-corpus seed contents shown in the expandable tables on the homepage.
window.CORPORA_ROWS = {
"1-cs": [
{
"stratum": "Computer Science",
"company": "",
"type": "paper",
"source": "arXiv (Cornell University)",
"title": "Deep reinforcement learning from human preferences",
"year": "2017",
"url": "https://openalex.org/W2626804490",
"accessible": "true"
},
{
"stratum": "Computer Science",
"company": "",
"type": "paper",
"source": "Science Robotics",
"title": "In situ bidirectional human-robot value alignment",
"year": "2022",
"url": "https://openalex.org/W4285392457",
"accessible": "true"
},
{
"stratum": "Computer Science",
"company": "",
"type": "paper",
"source": "arXiv (Cornell University)",
"title": "AI Alignment: A Comprehensive Survey",
"year": "2023",
"url": "https://openalex.org/W4388274718",
"accessible": "true"
},
{
"stratum": "Computer Science",
"company": "",
"type": "paper",
"source": "CHI Conference on Human Factors in Computing Systems",
"title": "Shared Interest: Measuring Human-AI Alignment to Identify Recurring Patterns in Model Behavior",
"year": "2022",
"url": "https://openalex.org/W4224980442",
"accessible": "true"
},
{
"stratum": "Computer Science",
"company": "",
"type": "paper",
"source": "Philosophical Studies",
"title": "Beyond Preferences in AI Alignment",
"year": "2024",
"url": "https://openalex.org/W4404200702",
"accessible": "true"
},
{
"stratum": "Political Science",
"company": "",
"type": "paper",
"source": "The RUSI Journal",
"title": "What is the State of Artificial Intelligence Governance Globally?",
"year": "2019",
"url": "https://openalex.org/W2990856437",
"accessible": "true"
},
{
"stratum": "Political Science",
"company": "",
"type": "paper",
"source": "Policy Sciences",
"title": "The politics of Artificial Intelligence regulation and governance reform in the European Union",
"year": "2022",
"url": "https://openalex.org/W4214919116",
"accessible": "true"
},
{
"stratum": "Political Science",
"company": "",
"type": "paper",
"source": "Proceedings of the AAAI/ACM Conference on AI Ethics and Society",
"title": "Should Artificial Intelligence Governance be Centralised?",
"year": "2020",
"url": "https://openalex.org/W3005462201",
"accessible": "true"
},
{
"stratum": "Political Science",
"company": "",
"type": "paper",
"source": "AI and Ethics",
"title": "Artificial intelligence, the common good, and the democratic deficit in AI governance",
"year": "2024",
"url": "https://openalex.org/W4398208103",
"accessible": "true"
},
{
"stratum": "Political Science",
"company": "",
"type": "paper",
"source": "SSRN Electronic Journal",
"title": "Law Informs Code: A Legal Informatics Approach to Aligning Artificial Intelligence with Humans",
"year": "2022",
"url": "https://openalex.org/W4297840560",
"accessible": "true"
},
{
"stratum": "Psychology",
"company": "",
"type": "paper",
"source": "Nature",
"title": "The Moral Machine experiment",
"year": "2018",
"url": "https://openalex.org/W2896252141",
"accessible": "true"
},
{
"stratum": "Psychology",
"company": "",
"type": "paper",
"source": "Cognition",
"title": "People are averse to machines making moral decisions",
"year": "2018",
"url": "https://openalex.org/W2886363025",
"accessible": "true"
},
{
"stratum": "Psychology",
"company": "",
"type": "paper",
"source": "The Philosophical Quarterly",
"title": "Understanding Artificial Agency",
"year": "2024",
"url": "https://openalex.org/W4391592270",
"accessible": "true"
},
{
"stratum": "Psychology",
"company": "",
"type": "paper",
"source": "AI & Society",
"title": "Could artificial intelligence have consciousness? Some perspectives from neurology and parapsychology",
"year": "2021",
"url": "https://openalex.org/W3217342481",
"accessible": "true"
},
{
"stratum": "Economics",
"company": "",
"type": "paper",
"source": "National Bureau of Economic Research",
"title": "Artificial Intelligence and Its Implications for Income Distribution and Unemployment",
"year": "2017",
"url": "https://openalex.org/W2776311290",
"accessible": "true"
},
{
"stratum": "Economics",
"company": "",
"type": "paper",
"source": "RePEc: Research Papers in Economics",
"title": "The Economics of Artificial Intelligence: An Agenda",
"year": "2019",
"url": "https://openalex.org/W2890116734",
"accessible": "true"
},
{
"stratum": "Economics",
"company": "",
"type": "paper",
"source": "National Bureau of Economic Research",
"title": "The Moral Preferences of Investors: Experimental Evidence",
"year": "2022",
"url": "https://openalex.org/W4205434771",
"accessible": "true"
},
{
"stratum": "Economics",
"company": "",
"type": "paper",
"source": "TSpace",
"title": "Incomplete Contracting and AI Alignment",
"year": "2019",
"url": "https://openalex.org/W2963086506",
"accessible": "true"
},
{
"stratum": "Philosophy",
"company": "",
"type": "paper",
"source": "Harvard Data Science Review",
"title": "A Unified Framework of Five Principles for AI in Society",
"year": "2019",
"url": "https://openalex.org/W2954266614",
"accessible": "true"
},
{
"stratum": "Philosophy",
"company": "",
"type": "paper",
"source": "Cambridge University Press eBooks",
"title": "The ethics of artificial intelligence",
"year": "2014",
"url": "https://openalex.org/W2506282302",
"accessible": "true"
},
{
"stratum": "Philosophy",
"company": "",
"type": "paper",
"source": "Minds and Machines",
"title": "Artificial Intelligence, Values, and Alignment",
"year": "2020",
"url": "https://openalex.org/W3002093512",
"accessible": "true"
},
{
"stratum": "Philosophy",
"company": "",
"type": "paper",
"source": "TU/e Research Portal",
"title": "Ethics of artificial intelligence and robotics",
"year": "2020",
"url": "https://openalex.org/W3022125597",
"accessible": "true"
}
],
"2-company": [
{
"stratum": "research",
"company": "anthropic",
"type": "paper",
"source": "",
"title": "Constitutional AI: Harmlessness from AI Feedback",
"year": "2022",
"url": "https://arxiv.org/abs/2212.08073",
"accessible": "True"
},
{
"stratum": "research",
"company": "anthropic",
"type": "paper",
"source": "",
"title": "Sleeper Agents: Training Deceptive LLMs that Persist Through Safety Training",
"year": "2024",
"url": "https://arxiv.org/abs/2401.05566",
"accessible": "True"
},
{
"stratum": "research",
"company": "anthropic",
"type": "paper",
"source": "",
"title": "Alignment faking in large language models",
"year": "2024",
"url": "https://arxiv.org/abs/2412.14093",
"accessible": "True"
},
{
"stratum": "research",
"company": "anthropic",
"type": "paper",
"source": "",
"title": "Natural Emergent Misalignment from Reward Hacking in Production RL",
"year": "2025",
"url": "https://arxiv.org/abs/2511.18397",
"accessible": "True"
},
{
"stratum": "research",
"company": "anthropic",
"type": "paper",
"source": "",
"title": "Model Spec Midtraining: Improving How Alignment Training Generalizes",
"year": "2026",
"url": "https://arxiv.org/abs/2605.02087",
"accessible": "True"
},
{
"stratum": "public",
"company": "anthropic",
"type": "webpage",
"source": "",
"title": "Core Views on AI Safety: When, Why, What, and How",
"year": "2023",
"url": "https://www.anthropic.com/news/core-views-on-ai-safety",
"accessible": "True"
},
{
"stratum": "public",
"company": "anthropic",
"type": "framework",
"source": "",
"title": "Anthropic's Responsible Scaling Policy (v3.3)",
"year": "2026",
"url": "https://www.anthropic.com/responsible-scaling-policy",
"accessible": "True"
},
{
"stratum": "public",
"company": "anthropic",
"type": "spec",
"source": "",
"title": "Claude's Constitution",
"year": "2026",
"url": "https://www.anthropic.com/constitution",
"accessible": "True"
},
{
"stratum": "public",
"company": "anthropic",
"type": "blog",
"source": "",
"title": "Collective Constitutional AI: Aligning a Language Model with Public Input",
"year": "2023",
"url": "https://www.anthropic.com/research/collective-constitutional-ai-aligning-a-language-model-with-public-input",
"accessible": "True"
},
{
"stratum": "research",
"company": "openai",
"type": "paper",
"source": "",
"title": "Training language models to follow instructions with human feedback (InstructGPT)",
"year": "2022",
"url": "https://arxiv.org/abs/2203.02155",
"accessible": "True"
},
{
"stratum": "research",
"company": "openai",
"type": "paper",
"source": "",
"title": "Deliberative Alignment: Reasoning Enables Safer Language Models",
"year": "2024",
"url": "https://arxiv.org/abs/2412.16339",
"accessible": "True"
},
{
"stratum": "research",
"company": "openai",
"type": "paper",
"source": "",
"title": "Monitoring Reasoning Models for Misbehavior and the Risks of Promoting Obfuscation",
"year": "2025",
"url": "https://arxiv.org/abs/2503.11926",
"accessible": "True"
},
{
"stratum": "research",
"company": "openai",
"type": "paper",
"source": "",
"title": "Persona Features Control Emergent Misalignment",
"year": "2025",
"url": "https://arxiv.org/abs/2506.19823",
"accessible": "True"
},
{
"stratum": "public",
"company": "openai",
"type": "spec",
"source": "",
"title": "OpenAI Model Spec",
"year": "2025",
"url": "https://model-spec.openai.com/",
"accessible": "True"
},
{
"stratum": "public",
"company": "openai",
"type": "framework",
"source": "",
"title": "OpenAI Preparedness Framework (Version 2)",
"year": "2025",
"url": "https://openai.com/index/updating-our-preparedness-framework/",
"accessible": "True"
},
{
"stratum": "public",
"company": "openai",
"type": "blog",
"source": "",
"title": "Our approach to alignment research",
"year": "2022",
"url": "https://openai.com/index/our-approach-to-alignment-research/",
"accessible": "True"
},
{
"stratum": "public",
"company": "openai",
"type": "webpage",
"source": "",
"title": "How we think about safety and alignment",
"year": "2025",
"url": "https://openai.com/safety/how-we-think-about-safety-alignment/",
"accessible": "False"
},
{
"stratum": "public",
"company": "openai",
"type": "blog",
"source": "",
"title": "Collective alignment: public input on our Model Spec (Aug 2025 updates)",
"year": "2025",
"url": "https://openai.com/index/collective-alignment-aug-2025-updates/",
"accessible": "False"
},
{
"stratum": "research",
"company": "deepmind",
"type": "paper",
"source": "",
"title": "Scalable agent alignment via reward modeling: a research direction",
"year": "2018",
"url": "https://arxiv.org/abs/1811.07871",
"accessible": "True"
},
{
"stratum": "research",
"company": "deepmind",
"type": "paper",
"source": "",
"title": "An Approach to Technical AGI Safety and Security",
"year": "2025",
"url": "https://arxiv.org/abs/2504.01849",
"accessible": "True"
},
{
"stratum": "research",
"company": "deepmind",
"type": "paper",
"source": "",
"title": "On scalable oversight with weak LLMs judging strong LLMs",
"year": "2024",
"url": "https://arxiv.org/abs/2407.04622",
"accessible": "True"
},
{
"stratum": "research",
"company": "deepmind",
"type": "paper",
"source": "",
"title": "Chain of Thought Monitorability: A New and Fragile Opportunity for AI Safety",
"year": "2025",
"url": "https://arxiv.org/abs/2507.11473",
"accessible": "True"
},
{
"stratum": "research",
"company": "deepmind",
"type": "paper",
"source": "",
"title": "To Mask or to Mirror: Human-AI Alignment in Collective Reasoning",
"year": "2025",
"url": "https://arxiv.org/abs/2510.01924",
"accessible": "True"
},
{
"stratum": "public",
"company": "deepmind",
"type": "framework",
"source": "",
"title": "Frontier Safety Framework (Version 3.1)",
"year": "2026",
"url": "https://deepmind.google/blog/strengthening-our-frontier-safety-framework/",
"accessible": "True"
},
{
"stratum": "public",
"company": "deepmind",
"type": "blog",
"source": "",
"title": "Taking a responsible path to AGI",
"year": "2025",
"url": "https://deepmind.google/blog/taking-a-responsible-path-to-agi/",
"accessible": "True"
},
{
"stratum": "research",
"company": "meta",
"type": "paper",
"source": "",
"title": "Llama Guard: LLM-based Input-Output Safeguard for Human-AI Conversations",
"year": "2023",
"url": "https://arxiv.org/abs/2312.06674",
"accessible": "True"
},
{
"stratum": "research",
"company": "meta",
"type": "paper",
"source": "",
"title": "Safety Alignment of LMs via Non-cooperative Games (AdvGame)",
"year": "2025",
"url": "https://arxiv.org/abs/2512.20806",
"accessible": "True"
},
{
"stratum": "research",
"company": "meta",
"type": "paper",
"source": "",
"title": "The Perfect Blend: Redefining RLHF with Mixture of Judges (CGPO)",
"year": "2024",
"url": "https://arxiv.org/abs/2409.20370",
"accessible": "True"
},
{
"stratum": "research",
"company": "meta",
"type": "paper",
"source": "",
"title": "Beyond Reward Hacking: Causal Rewards for Large Language Model Alignment",
"year": "2025",
"url": "https://arxiv.org/abs/2501.09620",
"accessible": "True"
},
{
"stratum": "research",
"company": "meta",
"type": "paper",
"source": "",
"title": "FLAME: Factuality-Aware Alignment for Large Language Models",
"year": "2024",
"url": "https://arxiv.org/abs/2405.01525",
"accessible": "True"
},
{
"stratum": "public",
"company": "meta",
"type": "blog",
"source": "",
"title": "Scaling How We Build and Test Our Most Advanced AI",
"year": "2026",
"url": "https://ai.meta.com/blog/scaling-how-we-build-test-advanced-ai/",
"accessible": "True"
},
{
"stratum": "public",
"company": "meta",
"type": "framework",
"source": "",
"title": "Meta Frontier AI / Advanced AI Scaling Framework (v2)",
"year": "2025",
"url": "https://ai.meta.com/static-resource/Meta_Advanced-AI-Scaling-Framework-v2/",
"accessible": "False"
},
{
"stratum": "research",
"company": "microsoft",
"type": "paper",
"source": "",
"title": "Controllable Safety Alignment: Inference-Time Adaptation to Diverse Safety Requirements",
"year": "2024",
"url": "https://arxiv.org/abs/2410.08968",
"accessible": "True"
},
{
"stratum": "research",
"company": "microsoft",
"type": "paper",
"source": "",
"title": "Contextual Integrity in LLMs via Reasoning and Reinforcement Learning",
"year": "2025",
"url": "https://arxiv.org/abs/2506.04245",
"accessible": "True"
},
{
"stratum": "research",
"company": "microsoft",
"type": "paper",
"source": "",
"title": "Privacy in Action: Realistic Privacy Mitigation and Evaluation for LLM-Powered Agents",
"year": "2025",
"url": "https://arxiv.org/abs/2509.17488",
"accessible": "True"
},
{
"stratum": "research",
"company": "microsoft",
"type": "report",
"source": "",
"title": "Phi-4-reasoning Technical Report",
"year": "2025",
"url": "https://arxiv.org/abs/2504.21318",
"accessible": "True"
},
{
"stratum": "public",
"company": "microsoft",
"type": "spec",
"source": "",
"title": "Microsoft Responsible AI Standard, v2: General Requirements",
"year": "2022",
"url": "https://blogs.microsoft.com/wp-content/uploads/prod/sites/5/2022/06/Microsoft-Responsible-AI-Standard-v2-General-Requirements-3.pdf",
"accessible": "True"
},
{
"stratum": "public",
"company": "microsoft",
"type": "essay",
"source": "",
"title": "Towards Humanist Superintelligence",
"year": "2025",
"url": "https://microsoft.ai/news/towards-humanist-superintelligence/",
"accessible": "True"
},
{
"stratum": "public",
"company": "microsoft",
"type": "framework",
"source": "",
"title": "Microsoft Frontier Governance Framework",
"year": "2025",
"url": "https://cdn-dynmedia-1.microsoft.com/is/content/microsoftcorp/microsoft/final/en-us/microsoft-brand/documents/Microsoft-Frontier-Governance-Framework.pdf",
"accessible": "True"
},
{
"stratum": "public",
"company": "microsoft",
"type": "report",
"source": "",
"title": "2025 Responsible AI Transparency Report",
"year": "2025",
"url": "https://www.microsoft.com/en-us/corporate-responsibility/responsible-ai-transparency-report/",
"accessible": "True"
}
],
"3-policy": [
{
"stratum": "supranational",
"company": "",
"type": "regulation",
"source": "European Union",
"title": "Regulation (EU) 2024/1689 — Artificial Intelligence Act",
"year": "2024",
"url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689",
"accessible": "true"
},
{
"stratum": "multilateral",
"company": "",
"type": "recommendation",
"source": "OECD",
"title": "Recommendation of the Council on Artificial Intelligence (AI Principles)",
"year": "2024",
"url": "https://legalinstruments.oecd.org/public/doc/648/648.en.pdf",
"accessible": "true"
},
{
"stratum": "multilateral",
"company": "",
"type": "recommendation",
"source": "UNESCO",
"title": "Recommendation on the Ethics of Artificial Intelligence",
"year": "2021",
"url": "https://www.unesco.org/en/articles/recommendation-ethics-artificial-intelligence",
"accessible": "true"
},
{
"stratum": "national",
"company": "",
"type": "framework",
"source": "NIST (US)",
"title": "AI Risk Management Framework 1.0",
"year": "2023",
"url": "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf",
"accessible": "true"
},
{
"stratum": "national",
"company": "",
"type": "framework",
"source": "NIST (US)",
"title": "AI RMF Generative AI Profile (NIST-AI-600-1)",
"year": "2024",
"url": "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf",
"accessible": "true"
},
{
"stratum": "national",
"company": "",
"type": "executive-order",
"source": "White House (US)",
"title": "Executive Order 14110: Safe, Secure, and Trustworthy AI",
"year": "2023",
"url": "https://www.federalregister.gov/documents/2023/11/01/2023-24283/safe-secure-and-trustworthy-development-and-use-of-artificial-intelligence",
"accessible": "true"
},
{
"stratum": "national",
"company": "",
"type": "blueprint",
"source": "White House OSTP (US)",
"title": "Blueprint for an AI Bill of Rights",
"year": "2022",
"url": "https://bidenwhitehouse.archives.gov/wp-content/uploads/2022/10/Blueprint-for-an-AI-Bill-of-Rights.pdf",
"accessible": "true"
},
{
"stratum": "national",
"company": "",
"type": "white-paper",
"source": "UK Government",
"title": "A pro-innovation approach to AI regulation",
"year": "2023",
"url": "https://www.gov.uk/government/publications/ai-regulation-a-pro-innovation-approach",
"accessible": "true"
},
{
"stratum": "multilateral",
"company": "",
"type": "declaration",
"source": "AI Safety Summit",
"title": "The Bletchley Declaration",
"year": "2023",
"url": "https://www.gov.uk/government/publications/ai-safety-summit-2023-the-bletchley-declaration",
"accessible": "true"
},
{
"stratum": "multilateral",
"company": "",
"type": "code-of-conduct",
"source": "G7",
"title": "Hiroshima Process International Guiding Principles & Code of Conduct",
"year": "2023",
"url": "https://digital-strategy.ec.europa.eu/en/library/hiroshima-process-international-guiding-principles-advanced-ai-system",
"accessible": "true"
},
{
"stratum": "multilateral",
"company": "",
"type": "treaty",
"source": "Council of Europe",
"title": "Framework Convention on AI, Human Rights, Democracy and the Rule of Law",
"year": "2024",
"url": "https://www.coe.int/en/web/artificial-intelligence/the-framework-convention-on-artificial-intelligence",
"accessible": "true"
},
{
"stratum": "multilateral",
"company": "",
"type": "report",
"source": "UN High-Level Advisory Body",
"title": "Governing AI for Humanity — Final Report",
"year": "2024",
"url": "https://www.un.org/en/ai-advisory-body",
"accessible": "true"
},
{
"stratum": "national",
"company": "",
"type": "regulation",
"source": "Cyberspace Administration of China",
"title": "Interim Measures for the Management of Generative AI Services",
"year": "2023",
"url": "https://www.chinalawtranslate.com/en/generative-ai-interim/",
"accessible": "true"
},
{
"stratum": "national",
"company": "",
"type": "strategy",
"source": "Federal Government of Germany",
"title": "Artificial Intelligence Strategy (2020 update)",
"year": "2020",
"url": "https://www.ki-strategie-deutschland.de/home.html",
"accessible": "true"
},
{
"stratum": "national",
"company": "",
"type": "directive",
"source": "Government of Canada",
"title": "Directive on Automated Decision-Making",
"year": "2023",
"url": "https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id=32592",
"accessible": "true"
},
{
"stratum": "national",
"company": "",
"type": "framework",
"source": "Singapore IMDA/PDPC",
"title": "Model AI Governance Framework for Generative AI",
"year": "2024",
"url": "https://aiverifyfoundation.sg/resources/mgf-gen-ai/",
"accessible": "true"
},
{
"stratum": "multilateral",
"company": "",
"type": "registry",
"source": "OECD.AI",
"title": "National AI Policies & Strategies registry",
"year": "2024",
"url": "https://oecd.ai/en/dashboards/overview",
"accessible": "true"
},
{
"stratum": "standards",
"company": "",
"type": "standard",
"source": "ISO/IEC",
"title": "ISO/IEC 42001:2023 — AI management system",
"year": "2023",
"url": "https://www.iso.org/standard/42001",
"accessible": "false"
}
],
"4-media": [
{
"stratum": "Global press",
"company": "",
"type": "outlet",
"source": "The Economist",
"title": "The Economist — Artificial intelligence",
"year": "",
"url": "https://www.economist.com/topics/artificial-intelligence",
"accessible": "true"
},
{
"stratum": "Global press",
"company": "",
"type": "outlet",
"source": "The New York Times",
"title": "The New York Times — Artificial Intelligence",
"year": "",
"url": "https://www.nytimes.com/topic/subject/artificial-intelligence",
"accessible": "true"
},
{
"stratum": "Global press",
"company": "",
"type": "outlet",
"source": "The Guardian",
"title": "The Guardian — Artificial intelligence (AI)",
"year": "",
"url": "https://www.theguardian.com/technology/artificialintelligenceai",
"accessible": "true"
},
{
"stratum": "Global press",
"company": "",
"type": "outlet",
"source": "Financial Times",
"title": "Financial Times — Artificial intelligence",
"year": "",
"url": "https://www.ft.com/artificial-intelligence",
"accessible": "true"
},
{
"stratum": "Global press",
"company": "",
"type": "outlet",
"source": "WIRED",
"title": "WIRED — Artificial Intelligence",
"year": "",
"url": "https://www.wired.com/tag/artificial-intelligence/",
"accessible": "true"
},
{
"stratum": "Global press",
"company": "",
"type": "outlet",
"source": "MIT Technology Review",
"title": "MIT Technology Review — Artificial intelligence",
"year": "",
"url": "https://www.technologyreview.com/topic/artificial-intelligence/",
"accessible": "true"
},
{
"stratum": "German press",
"company": "",
"type": "outlet",
"source": "Die Zeit",
"title": "Die Zeit — Künstliche Intelligenz",
"year": "",
"url": "https://www.zeit.de/thema/kuenstliche-intelligenz",
"accessible": "true"
},
{
"stratum": "German press",
"company": "",
"type": "outlet",
"source": "Frankfurter Allgemeine Zeitung",
"title": "FAZ — Künstliche Intelligenz",
"year": "",
"url": "https://www.faz.net/aktuell/wirtschaft/kuenstliche-intelligenz/",
"accessible": "true"
},
{
"stratum": "German press",
"company": "",
"type": "outlet",
"source": "Süddeutsche Zeitung",
"title": "Süddeutsche Zeitung — Künstliche Intelligenz",
"year": "",
"url": "https://www.sueddeutsche.de/thema/K%C3%BCnstliche_Intelligenz",
"accessible": "true"
},
{
"stratum": "German press",
"company": "",
"type": "outlet",
"source": "Der Spiegel",
"title": "Der Spiegel — Künstliche Intelligenz",
"year": "",
"url": "https://www.spiegel.de/thema/kuenstliche_intelligenz/",
"accessible": "true"
},
{
"stratum": "German press",
"company": "",
"type": "outlet",
"source": "Tagesschau (ARD)",
"title": "Tagesschau — Künstliche Intelligenz",
"year": "",
"url": "https://www.tagesschau.de/thema/k%C3%BCnstliche-intelligenz",
"accessible": "true"
}
]
};
