#!/usr/bin/env python3
"""Generate ../corpora-data.js for the homepage from the five manifest.csv files.

The homepage loads this via <script src="corpora-data.js"> (no fetch / CORS, so
it also works from file://). Re-run whenever a manifest changes:

    python3 corpora/build_site_data.py
"""
import csv
import json
import os

HERE = os.path.dirname(__file__)
ROOT = os.path.dirname(HERE)
CORPORA = ["1-cs", "2-company", "3-policy", "4-media"]

# Only the fields the homepage table needs (keeps the file small).
FIELDS = ["stratum", "company", "type", "source", "title", "year", "url", "accessible"]


def load(folder):
    path = os.path.join(HERE, folder, "manifest.csv")
    rows = []
    with open(path, encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            rows.append({k: (r.get(k) or "").strip() for k in FIELDS})
    return rows


def main():
    data = {folder: load(folder) for folder in CORPORA}
    out = os.path.join(ROOT, "corpora-data.js")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("// AUTO-GENERATED by corpora/build_site_data.py — do not hand-edit.\n")
        fh.write("// Per-corpus seed contents shown in the expandable tables on the homepage.\n")
        fh.write("window.CORPORA_ROWS = ")
        json.dump(data, fh, ensure_ascii=False, indent=0)
        fh.write(";\n")
    total = sum(len(v) for v in data.values())
    print(f"Wrote {out} — {total} rows across {len(data)} corpora")
    for k, v in data.items():
        print(f"  {k:12s} {len(v):4d}")


if __name__ == "__main__":
    main()
